In [2]:
##Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [4]:
##Data Collection
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

MessageError: Error: credential propagation was unsuccessful

In [ ]:
import os
print(os.listdir())

['.config', 'movies_metadata (1).csv', 'movies_metadata.csv', 'sample_data']

In [ ]:
##Load dataset
movies = pd.read_csv('movies_metadata.csv',
low_memory=False)

In [ ]:
movies.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [ ]:
print("Number of rows:", movies.shape[0])
print("Number of columns:", movies.shape[1])

Number of rows: 45466
Number of columns: 24

In [ ]:
movies.dtypes

adult                     object
belongs_to_collection     object
budget                    object
genres                    object
homepage                  object
id                        object
imdb_id                   object
original_language         object
original_title            object
overview                  object
popularity                object
poster_path               object
production_companies      object
production_countries      object
release_date              object
revenue                  float64
runtime                  float64
spoken_languages          object
status                    object
tagline                   object
title                     object
video                     object
vote_average             float64
vote_count               float64
dtype: object

In [ ]:
##Remove Duplicates
print("Duplicates before:" ,movies.duplicated().sum())
movies = movies.drop_duplicates()
print("Duplicates after:" ,movies.duplicated().sum())

Duplicates before: 17
Duplicates after: 0

In [ ]:
##Clean Movie IDs
movies["id"] = pd.to_numeric(
    movies["id"],
    errors="coerce"
)
movies = movies.dropna(subset=["id"]).copy()
movies["id"] = movies["id"].astype(int)

In [ ]:
movies = movies.drop_duplicates(subset="id")

In [ ]:
##Clean the movie titles
movies = movies.dropna(subset=["title"])

movies["title"] = movies["title"].astype(str).str.strip()

movies = movies[movies["title"] != ""]

In [ ]:
##Clean the release dates
movies["release_date"] = pd.to_datetime(
    movies["release_date"],
    errors="coerce"
)

movies["release_year"] = movies["release_date"].dt.year

In [ ]:
##Clean the numerival data
numeric_columns = [ "budget","revenue","runtime","popularity","vote_average","vote_count"
]

for column in numeric_columns:
    movies[column] = pd.to_numeric(
        movies[column],
        errors="coerce"
    )

In [ ]:
movies = movies[
    (movies["vote_average"] >= 0) &
    (movies["vote_average"] <= 10)
]

In [ ]:
movies = movies[
    movies["vote_count"].fillna(0) >= 0
]

In [ ]:
##Missing values
movies["budget"] = movies["budget"].replace(0, np.nan)
movies["revenue"] = movies["revenue"].replace(0, np.nan)
movies["runtime"] = movies["runtime"].replace(0, np.nan)

In [ ]:
movies["overview"] = movies["overview"].fillna("")
movies["original_language"] = (
    movies["original_language"].fillna("Unknown")
)
movies["original_title"] = (
    movies["original_title"].fillna(movies["title"])
)

In [ ]:
columns = ["id","title","original_title","overview","genres","original_language","release_date",
"release_year","runtime","popularity","vote_average","vote_count","budget","revenue"]

movies_clean = movies[columns].copy()

In [ ]:
##Sort dataset
movies_clean = movies_clean.sort_values(
    by=["release_year", "title"],
    ascending=[False, True]
)

In [ ]:
movies_clean = movies_clean.reset_index(drop=True)
movies_clean.head(20)

,id,title,original_title,overview,genres,original_language,release_date,release_year,runtime,popularity,vote_average,vote_count,budget,revenue
0,76600,Avatar 2,Avatar 2,A sequel to Avatar (2009).,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,2020-12-16,2020.0,NaN,6.020055,0.0,58.0,NaN,NaN
1,38700,Bad Boys for Life,Bad Boys for Life,The continuing adventures of Miami detectives ...,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",en,2018-11-07,2018.0,NaN,2.178546,0.0,12.0,NaN,NaN
2,302349,Iron Sky: The Coming Race,Iron Sky: The Coming Race,"Twenty years after the events of Iron Sky, the...","[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",en,2018-03-01,2018.0,NaN,1.917649,0.0,0.0,18000000.0,NaN
3,332283,Mary Shelley,Mary Shelley,The love affair between poet Percy Shelley and...,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,2018-04-25,2018.0,NaN,3.328261,0.0,1.0,NaN,NaN
4,412059,Mobile Homes,Mobile Homes,"In forgotten towns along the American border, ...","[{'id': 18, 'name': 'Drama'}]",en,2018-04-04,2018.0,105.0,0.155147,0.0,1.0,NaN,NaN
5,299782,The Other Side of the Wind,The Other Side of the Wind,"Orson Welles' unfinished masterpiece, restored...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",en,2018-12-31,2018.0,NaN,0.238154,0.0,1.0,12000000.0,NaN
6,342472,1 Mile to You,1 Mile to You,"After a teenager's friends die in an accident,...","[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,2017-04-07,2017.0,104.0,1.668699,6.7,29.0,NaN,NaN
7,416691,1 Night,1 Night,Thirty-something Elizabeth must decide whether...,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,2017-02-10,2017.0,76.0,2.491879,6.2,30.0,NaN,NaN
8,394770,11:55,11:55,"Upon his return home, a U.S. Marine must face ...","[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",en,2017-06-09,2017.0,80.0,0.722501,5.0,6.0,NaN,NaN
9,269795,2:22,2:22,A man's life is derailed when an ominous patte...,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",en,2017-06-29,2017.0,99.0,37.484577,5.5,277.0,NaN,422.0
10,346034,3 Idiotas,3 Idiotas,A group of friends embark on an adventure to f...,"[{'id': 10751, 'name': 'Family'}, {'id': 35, '...",es,2017-04-02,2017.0,106.0,0.959942,6.2,14.0,NaN,NaN
11,403119,47 Meters Down,47 Meters Down,Two sisters on Mexican vacation are trapped in...,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",en,2017-06-15,2017.0,89.0,52.854103,5.1,548.0,5500000.0,44235023.0
12,359749,78/52,78/52,78 shots. 52 cuts. The shower scene from PSYCHO.,"[{'id': 99, 'name': 'Documentary'}]",en,2017-11-03,2017.0,91.0,2.488539,0.0,4.0,NaN,NaN
13,398924,A Bag of Marbles,Un sac de billes,"In occupied France, Maurice and Joseph, two yo...","[{'id': 18, 'name': 'Drama'}]",fr,2017-01-18,2017.0,110.0,12.389862,7.8,100.0,NaN,NaN
14,340837,A Cure for Wellness,A Cure for Wellness,An ambitious young executive is sent to retrie...,"[{'id': 9648, 'name': 'Mystery'}, {'id': 53, '...",en,2017-02-15,2017.0,146.0,13.284360,6.0,939.0,40000000.0,26559557.0
15,381289,A Dog's Purpose,A Dog's Purpose,A dog goes on quest to discover his purpose in...,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",en,2017-01-19,2017.0,100.0,9.863789,6.6,657.0,22000000.0,194647323.0
16,375183,A Family Man,A Family Man,"Dane Jensen is a driven, Chicago-based headhun...","[{'id': 18, 'name': 'Drama'}]",en,2017-05-18,2017.0,108.0,8.844173,6.7,60.0,NaN,NaN
17,429191,A Fantastic Woman,Una mujer fantástica,A waitress and singer struggles to recover fro...,"[{'id': 18, 'name': 'Drama'}]",es,2017-04-06,2017.0,104.0,4.059329,7.2,13.0,NaN,NaN
18,413391,A Few Less Men,A Few Less Men,Travel plans for three men in ill-fitting wedd...,"[{'id': 35, 'name': 'Comedy'}]",en,2017-03-09,2017.0,96.0,1.475321,5.2,11.0,NaN,123899.0
19,428449,A Ghost Story,A Ghost Story,"Recently deceased, a white-sheeted ghost retur...","[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",en,2017-07-07,2017.0,92.0,24.339781,6.8,95.0,100000.0,15584255.0

In [ ]:
print("Final rows:", movies_clean.shape[0])
print("Final columns:", movies_clean.shape[1])
print("Duplicate rows:",movies_clean.duplicated().sum())
print("Duplicate movie IDs:",movies_clean["id"].duplicated().sum())

Final rows: 45430
Final columns: 14
Duplicate rows: 0
Duplicate movie IDs: 0

In [ ]:
movies_clean.isnull().sum()

id                       0
title                    0
original_title           0
overview                 0
genres                   0
original_language        0
release_date            84
release_year            84
runtime               1815
popularity               0
vote_average             0
vote_count               0
budget               36550
revenue              38032
dtype: int64

In [ ]:
##Remove columns with too many missing values
movies_clean = movies_clean.drop(columns=["budget", "revenue"]
)

In [ ]:
#Fill missing runtime with the median runtime
median_runtime = movies_clean["runtime"].median()
movies_clean["runtime"] = movies_clean["runtime"].fillna(median_runtime
)

In [ ]:
movies_clean.isnull().sum()

id                    0
title                 0
original_title        0
overview              0
genres                0
original_language     0
release_date         84
release_year         84
runtime               0
popularity            0
vote_average          0
vote_count            0
dtype: int64

In [ ]:
movies_clean = movies_clean.sort_values(
    by=["release_year", "title"],
    ascending=[False, True],
    na_position="last"
)

movies_clean = movies_clean.reset_index(drop=True)

In [ ]:
print("Final rows:", movies_clean.shape[0])
print("Final columns:", movies_clean.shape[1])
print("Duplicate rows:", movies_clean.duplicated().sum())
print("Duplicate IDs:", movies_clean["id"].duplicated().sum())

Final rows: 45430
Final columns: 12
Duplicate rows: 0
Duplicate IDs: 0

In [ ]:
movies_clean.head(20)

,id,title,original_title,overview,genres,original_language,release_date,release_year,runtime,popularity,vote_average,vote_count
0,76600,Avatar 2,Avatar 2,A sequel to Avatar (2009).,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,2020-12-16,2020.0,95.0,6.020055,0.0,58.0
1,38700,Bad Boys for Life,Bad Boys for Life,The continuing adventures of Miami detectives ...,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",en,2018-11-07,2018.0,95.0,2.178546,0.0,12.0
2,302349,Iron Sky: The Coming Race,Iron Sky: The Coming Race,"Twenty years after the events of Iron Sky, the...","[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",en,2018-03-01,2018.0,95.0,1.917649,0.0,0.0
3,332283,Mary Shelley,Mary Shelley,The love affair between poet Percy Shelley and...,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,2018-04-25,2018.0,95.0,3.328261,0.0,1.0
4,412059,Mobile Homes,Mobile Homes,"In forgotten towns along the American border, ...","[{'id': 18, 'name': 'Drama'}]",en,2018-04-04,2018.0,105.0,0.155147,0.0,1.0
5,299782,The Other Side of the Wind,The Other Side of the Wind,"Orson Welles' unfinished masterpiece, restored...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",en,2018-12-31,2018.0,95.0,0.238154,0.0,1.0
6,342472,1 Mile to You,1 Mile to You,"After a teenager's friends die in an accident,...","[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,2017-04-07,2017.0,104.0,1.668699,6.7,29.0
7,416691,1 Night,1 Night,Thirty-something Elizabeth must decide whether...,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",en,2017-02-10,2017.0,76.0,2.491879,6.2,30.0
8,394770,11:55,11:55,"Upon his return home, a U.S. Marine must face ...","[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",en,2017-06-09,2017.0,80.0,0.722501,5.0,6.0
9,269795,2:22,2:22,A man's life is derailed when an ominous patte...,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",en,2017-06-29,2017.0,99.0,37.484577,5.5,277.0
10,346034,3 Idiotas,3 Idiotas,A group of friends embark on an adventure to f...,"[{'id': 10751, 'name': 'Family'}, {'id': 35, '...",es,2017-04-02,2017.0,106.0,0.959942,6.2,14.0
11,403119,47 Meters Down,47 Meters Down,Two sisters on Mexican vacation are trapped in...,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",en,2017-06-15,2017.0,89.0,52.854103,5.1,548.0
12,359749,78/52,78/52,78 shots. 52 cuts. The shower scene from PSYCHO.,"[{'id': 99, 'name': 'Documentary'}]",en,2017-11-03,2017.0,91.0,2.488539,0.0,4.0
13,398924,A Bag of Marbles,Un sac de billes,"In occupied France, Maurice and Joseph, two yo...","[{'id': 18, 'name': 'Drama'}]",fr,2017-01-18,2017.0,110.0,12.389862,7.8,100.0
14,340837,A Cure for Wellness,A Cure for Wellness,An ambitious young executive is sent to retrie...,"[{'id': 9648, 'name': 'Mystery'}, {'id': 53, '...",en,2017-02-15,2017.0,146.0,13.284360,6.0,939.0
15,381289,A Dog's Purpose,A Dog's Purpose,A dog goes on quest to discover his purpose in...,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",en,2017-01-19,2017.0,100.0,9.863789,6.6,657.0
16,375183,A Family Man,A Family Man,"Dane Jensen is a driven, Chicago-based headhun...","[{'id': 18, 'name': 'Drama'}]",en,2017-05-18,2017.0,108.0,8.844173,6.7,60.0
17,429191,A Fantastic Woman,Una mujer fantástica,A waitress and singer struggles to recover fro...,"[{'id': 18, 'name': 'Drama'}]",es,2017-04-06,2017.0,104.0,4.059329,7.2,13.0
18,413391,A Few Less Men,A Few Less Men,Travel plans for three men in ill-fitting wedd...,"[{'id': 35, 'name': 'Comedy'}]",en,2017-03-09,2017.0,96.0,1.475321,5.2,11.0
19,428449,A Ghost Story,A Ghost Story,"Recently deceased, a white-sheeted ghost retur...","[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",en,2017-07-07,2017.0,92.0,24.339781,6.8,95.0

##**Ratings.csv**

In [ ]:
from google.colab import files

uploaded = files.upload()

In [ ]:
ratings = pd.read_csv("ratings_small.csv")
print("Rows:", ratings.shape[0])
print("Columns:", ratings.shape[1])

ratings.head()

In [ ]:
ratings.shape

In [ ]:
ratings.info()

In [ ]:
##Check missing values
ratings.isnull().sum()

In [ ]:
##Clean userId and movieId

ratings["userId"] = pd.to_numeric(ratings["userId"],errors="coerce"
)

ratings["movieId"] = pd.to_numeric(ratings["movieId"],errors="coerce"
)

ratings = ratings.dropna(subset=["userId", "movieId"]).copy()

ratings["userId"] = ratings["userId"].astype(int)
ratings["movieId"] = ratings["movieId"].astype(int)

In [ ]:
# Check rating range
print("Minimum rating:", ratings["rating"].min())
print("Maximum rating:", ratings["rating"].max())
print("\nUnique rating values:")
print(sorted(ratings["rating"].unique()))

In [ ]:
#Check for invalid ratings

invalid_ratings = ratings[
    (ratings["rating"] < 0) |
    (ratings["rating"] > 5)
]

print("Invalid ratings:", len(invalid_ratings))

In [ ]:
# Check for duplicates
print("Duplicate rows:", ratings.duplicated().sum())

print("Duplicate user-movie ratings:",ratings.duplicated(
        subset=["userId", "movieId"]
    ).sum()
)

In [ ]:
# Convert timestamp to a readable date
ratings["timestamp"] = pd.to_datetime(
    ratings["timestamp"],
    unit="s",
    errors="coerce"
)

print(ratings.head())

In [ ]:
print("Missing timestamps:", ratings["timestamp"].isnull().sum())

In [ ]:
##Check whether rating movie IDs exist in the movie dataset

matched_movies = ratings["movieId"].isin(movies_clean["id"])
print("Matching movie IDs:", matched_movies.sum())
print("Unmatched movie IDs:", (~matched_movies).sum())

In [ ]:
unmatched_ids = ratings.loc[
    ~ratings["movieId"].isin(movies_clean["id"]),
    "movieId"]

print("Number of unmatched IDs:", len(unmatched_ids))
print("\nFirst 20 unmatched IDs:")
print(unmatched_ids.head(20).tolist())

In [ ]:
print("Smallest unmatched ID:", unmatched_ids.min())
print("Largest unmatched ID:", unmatched_ids.max())

In [ ]:
print("Movie IDs in movies_clean:")
print(movies_clean["id"].head(20).tolist())
print("\nMovie IDs in ratings:")
print(ratings["movieId"].head(20).tolist())

In [ ]:
print("Number of unique movie IDs in movies_clean:",
      movies_clean["id"].nunique())

print("Number of unique movie IDs in ratings:",
      ratings["movieId"].nunique())

In [ ]:
#Calculate movie ID matching percentage

matching_count = ratings["movieId"].isin(movies_clean["id"]).sum()
total_ratings = len(ratings)

match_percentage = (matching_count / total_ratings) * 100

print("Matching ratings:", matching_count)
print("Total ratings:", total_ratings)
print(f"Match percentage: {match_percentage:.2f}%")

In [ ]:
matching_movies = ratings.loc[
    ratings["movieId"].isin(movies_clean["id"]),
    "movieId"
].nunique()

unmatched_movies = ratings.loc[
    ~ratings["movieId"].isin(movies_clean["id"]),
    "movieId"
].nunique()

print("Unique matching movie IDs:", matching_movies)
print("Unique unmatched movie IDs:", unmatched_movies)

In [ ]:
from google.colab import files
import pandas as pd

uploaded = files.upload()

In [ ]:
links = pd.read_csv("links.csv")
print(links.shape)
links.head()

In [ ]:
# Clean the ID columns
links["movieId"] = pd.to_numeric(
    links["movieId"],
    errors="coerce"
)

links["tmdbId"] = pd.to_numeric(
    links["tmdbId"],
    errors="coerce"
)

links = links.dropna(
    subset=["movieId"]
).copy()

links["movieId"] = links["movieId"].astype(int)

In [ ]:
print("Missing TMDB IDs:", links["tmdbId"].isnull().sum())

In [ ]:
ratings_linked = ratings.merge(
    links[["movieId", "tmdbId"]],
    on="movieId",
    how="left"
)

print("Ratings after linking:", ratings_linked.shape)
ratings_linked.head()

In [ ]:
print("Ratings with TMDB ID:",ratings_linked["tmdbId"].notna().sum()
)

print("Ratings without TMDB ID:",ratings_linked["tmdbId"].isna().sum()
)

In [ ]:
ratings_movies = ratings_linked.merge(
    movies_clean,
    left_on="tmdbId",
    right_on="id",
    how="inner"
)

print("Final matched ratings:", len(ratings_movies))
print("Final columns:", ratings_movies.columns.tolist())

In [ ]:
print("Duplicate user-movie ratings:",ratings_movies.duplicated(subset=["userId", "movieId"]).sum()
)

In [ ]:
ratings_clean = ratings_movies[
    [
        "userId",
        "movieId",
        "rating",
        "timestamp",
        "id",
        "title"
    ]
].copy()

ratings_clean = ratings_clean.rename(
    columns={"id": "tmdbId"}
)

print("Final ratings dataset:", ratings_clean.shape)
ratings_clean.head()

In [ ]:
print("Missing values:")
print(ratings_clean.isnull().sum())

print("\nDuplicate rows:")
print(ratings_clean.duplicated().sum())

print("\nRating range:")
print(
    ratings_clean["rating"].min(),
    "to",
    ratings_clean["rating"].max()
)

In [ ]:
ratings_clean.to_csv(
    "ratings_cleaned.csv",
    index=False
)

print("ratings_cleaned.csv saved successfully.")

In [ ]:
import matplotlib.pyplot as plt
rating_counts = ratings_clean["rating"].value_counts().sort_index()
plt.figure(figsize=(8, 5))
plt.bar(
    rating_counts.index.astype(str),
    rating_counts.values
)
plt.xlabel("Rating")
plt.ylabel("Number of Ratings")
plt.title("Distribution of Movie Ratings")
plt.show()

In [ ]:
print("Average rating:", ratings_clean["rating"].mean())
print("Median rating:", ratings_clean["rating"].median())
print("Minimum rating:", ratings_clean["rating"].min())
print("Maximum rating:", ratings_clean["rating"].max()

In [ ]:
movie_rating_counts = (
    ratings_clean
    .groupby(["movieId", "title"])
    .size()
    .reset_index(name="rating_count")
    .sort_values(
        "rating_count",
        ascending=False
    )
)
movie_rating_counts.head(10)

In [ ]:
top_movies = movie_rating_counts.head(10)
plt.figure(figsize=(10, 6))
plt.barh(
    top_movies["title"].iloc[::-1],
    top_movies["rating_count"].iloc[::-1]
)
plt.xlabel("Number of Ratings")
plt.ylabel("Movie")
plt.title("Top 10 Most-Rated Movies")
plt.show()

In [ ]:
movie_average_ratings = (
    ratings_clean
    .groupby(["movieId", "title"])["rating"]
    .agg(
    )
        average_rating="mean",
        rating_count="count"
    .reset_index()
)
movie_average_ratings.head()

In [ ]:
highly_rated_movies = movie_average_ratings[
    movie_average_ratings["rating_count"] >= 20
].sort_values(
    "average_rating",
    ascending=False
)
highly_rated_movies.head(10)

In [ ]:
user_rating_counts = (
    ratings_clean
    .groupby("userId")
    .size()
    .reset_index(name="rating_count")
)
user_rating_counts.head()

In [ ]:
user_rating_counts = (
    ratings_clean
    .groupby("userId")
    .size()
    .reset_index(name="rating_count")
)
user_rating_counts.head()

In [ ]:
plt.figure(figsize=(8, 5))
plt.hist(
    user_rating_counts["rating_count"],
    bins=30
)
plt.xlabel("Number of Ratings per User")
plt.ylabel("Number of Users")
plt.title("User Rating Activity")
plt.show()

In [ ]:
number_of_users = ratings_clean["userId"].nunique()
number_of_movies = ratings_clean["movieId"].nunique()
number_of_ratings = len(ratings_clean)
total_possible_ratings = (
    number_of_users * number_of_movies
)
sparsity = (
    1
    (number_of_ratings / total_possible_ratings)
) * 100
print("Number of users:", number_of_users)
print("Number of movies:", number_of_movies)
print("Number of ratings:", number_of_ratings)
print(f"Sparsity: {sparsity:.2f}%")

In [ ]:
import ast

In [ ]:
def extract_genres(genre_data):
    try:
        genres = ast.literal_eval(genre_data)
        if isinstance(genres, list):
            return [
                genre["name"]
                for genre in genres
                if isinstance(genre, dict) and "name" in genre
            ]
        return []
    except:
        return []
movies_clean["genre_list"] = (
    movies_clean["genres"]
    .apply(extract_genres)
)
movies_clean[["title", "genre_list"]].head()

In [ ]:
from collections import Counter
genre_counts = Counter()
for genres in movies_clean["genre_list"]:
    genre_counts.update(genres)
genre_counts = pd.DataFrame(
    genre_counts.items(),
    columns=["genre", "movie_count"]
).sort_values(
    "movie_count",
    ascending=False
)
genre_counts.head(10)

In [ ]:
top_genres = genre_counts.head(10)
plt.figure(figsize=(10, 6))
plt.barh(
    top_genres["genre"].iloc[::-1],
    top_genres["movie_count"].iloc[::-1]
)
plt.xlabel("Number of Movies")
plt.ylabel("Genre")
plt.title("Top 10 Movie Genres")
plt.show()

In [ ]:
user_features = (
    ratings_clean
    .groupby("userId")["rating"]
    .agg(
        user_average_rating="mean",
        user_rating_count="count"
    )
    .reset_index()
)
user_features.head()

In [ ]:
import ast
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
from sklearn.preprocessing import normalize
from scipy.sparse import hstack

In [ ]:
def parse_genres(value):
  try:
    return [g["name"] for g in ast.literal_eval(value)]
  except:
    return []
cb = movies_clean.reset_index(drop=True).copy()
cb["genre_list"] = cb["genres"].apply(parse_genres)\
cb ["genre_text"] = cb["genre_list"].apply(
    lambda gs: " ".join(g.replace(" ", "") for g in gs)
)
print("Movies with no genres:", (cb["genre_list"].str.len() == 0).sum())
cb[["title", "genre_list"]].head()